<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-U8CM5F9C" ignored="1" name="Default test(failed)" tests="2" failures="1" timestamp="2021-03-31T22:35:21 IST" time="0.08" errors="0">
  <testcase name="tC2" time="0.012" classname="TestNG_Rerun_failed_test_cases.TestNG_Rerun_Failed_Tc_EX1"/>
  <testcase name="tC1" time="0.006" classname="TestNG_Rerun_failed_test_cases.TestNG_Rerun_Failed_Tc_EX1">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TestNG_Rerun_failed_test_cases.TestNG_Rerun_Failed_Tc_EX1.tC1(TestNG_Rerun_Failed_Tc_EX1.java:12)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tC1 -->
  <testcase name="tC3" time="0.0" classname="TestNG_Rerun_failed_test_cases.TestNG_Rerun_Failed_Tc_EX1">
    <ignored/>
  </testcase> <!-- tC3 -->
</testsuite> <!-- Default test(failed) -->
