<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-U8CM5F9C" name="TestNG_Rerun_failed_test_cases_in_test_suite.TestNG_Rerun_Failed_Tc_EX1" tests="3" failures="1" timestamp="2021-03-31T23:33:22 IST" time="0.023" errors="0">
  <testcase name="tC1" time="0.016" classname="TestNG_Rerun_failed_test_cases_in_test_suite.TestNG_Rerun_Failed_Tc_EX1">
    <failure type="java.lang.AssertionError" message="assert fail">
      <![CDATA[java.lang.AssertionError: assert fail
at org.testng.Assert.fail(Assert.java:99)
at TestNG_Rerun_failed_test_cases_in_test_suite.TestNG_Rerun_Failed_Tc_EX1.tC1(TestNG_Rerun_Failed_Tc_EX1.java:12)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- tC1 -->
  <system-out/>
  <testcase name="tC2" time="0.007" classname="TestNG_Rerun_failed_test_cases_in_test_suite.TestNG_Rerun_Failed_Tc_EX1"/>
  <system-out>
running tc 2  </system-out>
  <testcase name="tC3" time="0.000" classname="TestNG_Rerun_failed_test_cases_in_test_suite.TestNG_Rerun_Failed_Tc_EX1"/>
  <system-out>
running tc 3  </system-out>
</testsuite> <!-- TestNG_Rerun_failed_test_cases_in_test_suite.TestNG_Rerun_Failed_Tc_EX1 -->
