<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-U8CM5F9C" name="TestNG_assert_verification_example.Assert_verifacatinon_example_1" tests="7" failures="1" timestamp="2021-04-16T11:38:05 IST" time="0.032" errors="0">
  <testcase name="Verification1" time="0.019" classname="TestNG_assert_verification_example.Assert_verifacatinon_example_1"/>
  <system-out/>
  <testcase name="Verification7" time="0.001" classname="TestNG_assert_verification_example.Assert_verifacatinon_example_1">
    <failure type="java.lang.AssertionError" message="test case is fail">
      <![CDATA[java.lang.AssertionError: test case is fail
at org.testng.Assert.fail(Assert.java:99)
at TestNG_assert_verification_example.Assert_verifacatinon_example_1.Verification7(Assert_verifacatinon_example_1.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Verification7 -->
  <system-out/>
  <testcase name="Verification2" time="0.001" classname="TestNG_assert_verification_example.Assert_verifacatinon_example_1"/>
  <system-out/>
  <testcase name="Verification4" time="0.002" classname="TestNG_assert_verification_example.Assert_verifacatinon_example_1"/>
  <system-out/>
  <testcase name="Verification6" time="0.005" classname="TestNG_assert_verification_example.Assert_verifacatinon_example_1"/>
  <system-out/>
  <testcase name="Verification3" time="0.003" classname="TestNG_assert_verification_example.Assert_verifacatinon_example_1"/>
  <system-out/>
  <testcase name="Verification5" time="0.001" classname="TestNG_assert_verification_example.Assert_verifacatinon_example_1"/>
  <system-out/>
</testsuite> <!-- TestNG_assert_verification_example.Assert_verifacatinon_example_1 -->
